### ISSUE TITLE
Question: Set DNS

### ISSUE THREAD

**Issue by kcvanderlinden** [KarlJorgensen/virgin-media-hub3#16]
First of all, great script!
I was wonderig however how to set the DNS (dns_servers) in my Arris version of the Dutch ConnectBox. With the command --help I only receive the parameter 'value' (along with three times the list retreived from property-list).

**Comment by andyrichardson** [comment]
I spent some time playing around with this. I've tried with and without autodns enabled but no dice

```
Hub Hub(hostname=192.168.0.1, username=admin) refused to set OID 1.3.6.1.4.1.4115.1.20.1.1.1.11.2.1.3.1: Response was {}
```

If you want to disable ISP DNS outright, you can run this command

```
python3 ./hub property-set wan_use_auto_dns False
```

Although this will cause all connected devices to have DNS failures until a DNS provider is manually configured (on the client device)

**Comment by kcvanderlinden** [comment]
Thanks for the reponse. The solution is not perfect, but that is due to the router. Thanks anyway.
